import Head from 'next/head';
import Image from 'next/image';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight } from '@fortawesome/free-solid-svg-icons';

export default function Home() {
  return (
    <div className="px-8 font-fira">
      <Head>
        <title>Next.js with Daisyui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-16 flex flex-col flex-1 justify-center items-center">
        <h1 className="m-0 text-6xl leading-5 text-center relative">
          Welcome to{' '}
          <a href="https://nextjs.org" className=" link link-hover link-accent ">
            Next.js!
          </a>
          <a href="https://daisyui.com" className=" w-max link link-hover link-secondary text-sm absolute right-1 top-12 ">
            w/ daisyUI!🌻
          </a>
        </h1>

        <aside className="flex gap-8 text-center my-16 text-2xl leading-6 items-center">
          Get started by editing
          <div className=" mockup-code bg-primary text-primary-content">
            <pre data-prefix="∟">
              <code>pages/index.js</code>
            </pre>
          </div>
        </aside>

        <div className=" flex flex-wrap items-center justify-center max-w-4xl text-neutral">
          <div className=" card max-w-sm m-4 bg-base-100 border-2 border-neutral ">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Documentation</h2>
              <p className=" text-xl">Find in-depth information about Next.js features and API.</p>
              <div className="card-actions justify-end">
                <a href="https://nextjs.org/docs" className="btn btn-accent">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>

          <div className=" card max-w-sm m-4 bg-base-100 border-2 border-neutral ">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Learn</h2>
              <p className=" text-xl">Learn about Next.js in an interactive course with quizzes!</p>
              <div className="card-actions justify-end">
                <a href="https://nextjs.org/learn" className="btn btn-accent">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>

          <div className=" card max-w-sm m-4 bg-base-100 border-2 border-neutral ">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Examples</h2>
              <p className=" text-xl">Discover and deploy boilerplate example Next.js projects.</p>
              <div className="card-actions justify-end">
                <a href="https://github.com/vercel/next.js/tree/canary/examples" className="btn btn-accent">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>

          <div className=" card max-w-sm m-4 bg-base-100 border-2 border-neutral ">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Deploy</h2>
              <p className=" text-xl">Instantly deploy your Next.js site to a public URL with Vercel.</p>
              <div className="card-actions justify-end">
                <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className="btn btn-accent ">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="flex flex-1 py-8 border-t-2 justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className=" flex flex-grow justify-center items-center"
        >
          Powered by
          <span className="h-4 ml-2">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
