import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowRight, faPlay } from '@fortawesome/free-solid-svg-icons';

import { useEffect } from 'react'
import { themeChange } from 'theme-change'


export default function Home() {

  useEffect(() => {
    themeChange(false)
  })

  return (
    <div className="px-8 font-fira">
      <Head>
        <title>Next.js with Daisyui</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className=" float-right pt-8 dropdown dropdown-end">
        <label tabIndex="0" className="btn m-1">Theme</label>
        <ul tabIndex="0" className="dropdown-content menu p-2 shadow bg-base-100 rounded-box w-52">
          <li><a data-set-theme="light">Light</a></li>
          <li><a data-set-theme="dark">Dark</a></li>
          <li><a data-set-theme="cupcake">Cupcake</a></li>
          <li><a data-set-theme="retro">Retro</a></li>
          <li><a data-set-theme="corporate">Corporate</a></li>
          <li><a data-set-theme="business">Business</a></li>
        </ul>
      </nav>

      <main className="min-h-screen py-16 flex flex-col flex-1 justify-center items-center">
        <h1 className="m-0 text-6xl leading-5 text-center relative">
          Welcome to{' '}
          <a href="https://nextjs.org" className=" link link-hover link-secondary">
            Next.js!
          </a>
          <a href="https://daisyui.com" className=" w-max link link-hover text-sm absolute right-1 top-12 ">
            w/ daisyUI!🌻
          </a>
        </h1>

        <aside className="flex gap-8 text-center my-16 text-2xl leading-6 items-center">
          Get started by editing
          <div className=" mockup-code bg-primary text-primary-content">
            <pre data-prefix="∟">
              <code>pages/index.js</code>
            </pre>
          </div>
        </aside>

        <div className=" flex flex-wrap items-center justify-center max-w-4xl text-base-content ">
          <div className=" card max-w-sm m-4 outline outline-base-content">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Documentation</h2>
              <p className=" text-xl">Find in-depth information about Next.js features and API.</p>
              <div className="card-actions justify-end">
                <a href="https://nextjs.org/docs" className="btn btn-accent">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>

          <div className=" card max-w-sm m-4 outline outline-base-content">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Learn</h2>
              <p className=" text-xl">Learn about Next.js in an interactive course with quizzes!</p>
              <div className="card-actions justify-end">
                <a href="https://nextjs.org/learn" className="btn btn-accent">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>

          <div className=" card max-w-sm m-4 outline outline-base-content ">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Examples</h2>
              <p className=" text-xl">Discover and deploy boilerplate example Next.js projects.</p>
              <div className="card-actions justify-end">
                <a href="https://github.com/vercel/next.js/tree/canary/examples" className="btn btn-accent">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>

          <div className=" card max-w-sm m-4 outline outline-base-content">
            <div className=" card-body">
              <h2 className=" card-title text-2xl">Deploy</h2>
              <p className=" text-xl">Instantly deploy your Next.js site to a public URL with Vercel.</p>
              <div className="card-actions justify-end">
                <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" className="btn btn-accent ">
                  <FontAwesomeIcon icon={faArrowRight} />
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>

      <footer className="flex flex-1 py-8 border-t-[3px] border-base-content justify-center items-center">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className=" flex flex-grow justify-center items-center"
        >
          Powered by
          <span className="ml-4 text-2xl text-base-content -rotate-90">
            <FontAwesomeIcon icon={faPlay} />
          </span>
        </a>
      </footer>
    </div>
  );
}
